<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
//use yii\grid\GridView;
use kartik\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\SapItem $model
*/

$this->title = 'Part No ' . $model->sap_partno;
$this->params['breadcrumbs'][] = ['label' => 'Sap Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->item_id, 'url' => ['view', 'item_id' => $model->item_id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud sap-item-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'item_id' => $model->item_id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'List SapItems', ['index'], ['class'=>'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
                <?= $model->sap_partno ?>            </h2>
        </div>

        <div class="panel-body">



    <?php $this->beginBlock('app\models\SapItem'); ?>

    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            //'item_id',
        'sap_partno',
        'description',
        'uom',
        'analyst_group',
        'analyst_desc',
        'issue_type_desc',
        'item_class',
        //'insert_type',
        //'flag',
    ],
    ]); ?>

    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'item_id' => $model->item_id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('WiParts'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Wi Parts',
            ['wi-part/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Wi Part',
            ['wi-part/create', 'WiPart' => ['sap_item_id' => $model->item_id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-WiParts', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-WiParts ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \kartik\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getWiParts(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-wiparts']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [
    		/* [
			    'class'      => 'kartik\grid\ActionColumn',
			    'template'   => '{view} {update}',
			    'contentOptions' => ['nowrap'=>'nowrap'],
			    'urlCreator' => function ($action, $model, $key, $index) {
			        // using the column name as key, not mapping to 'id' like the standard generator
			        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
			        $params[0] = 'wi-part' . '/' . $action;
			        return $params;
			    },
			    'buttons'    => [
			        
			    ],
			    'controller' => 'wi-part'
			], */
        //'wi_part_id',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class'=>'kartik\grid\ExpandRowColumn',
		'value'=>function ($model, $key, $index, $column) {
		return GridView::ROW_COLLAPSED;
		},
		'detail'=>function ($model, $key, $index, $column) {
			$master = $model->getMasterlist()->one();
			return Yii::$app->controller->renderPartial('detail-wi', ['model' => $master]);
		},
		'headerOptions'=>['class'=>'kartik-sheet-style'],
		'expandOneOnly'=>true,
],
[
	'class'=>'kartik\grid\DataColumn',
	'attribute' => 'masterlist_id',
	'value' => function ($model) {
		 if ($rel = $model->getMasterlist()->one()) {
		 	return Html::a($rel->doc_no, ['wi-masterlist/view', 'masterlist_id' => $rel->masterlist_id,], ['data-pjax' => 0]);
		} else {
			return '';
		}
	},
	'format' => 'raw', 
],
        //'flag',
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->sap_partno.'</b>',
    'content' => $this->blocks['app\models\SapItem'],
    'active'  => true,
],[
    'content' => $this->blocks['WiParts'],
    'label'   => '<small>Related WI <span class="badge badge-default">'.count($model->getWiParts()->asArray()->all()).'</span></small>',
    'active'  => false,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
