<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\WiRemark $model
*/

$wi_docno = $model->getHistory()->one()->getWi()->one()->wi_docno;

$this->title = 'Remark ';
$this->params['breadcrumbs'][] = ['label' => 'Wi Remarks', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';

?>
<div class="giiant-crud wi-remark-view">

    <!-- menu buttons -->
    <p class='pull-left' style='display: none;'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right" style='display: none;'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'List WiRemarks', ['index'], ['class'=>'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
                <?= $wi_docno ?>            </h2>
        </div>

        <div class="panel-body">



    <?php $this->beginBlock('app\models\WiRemark'); ?>

    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            //'id',
        //'user_id',
    		[
    		'attribute'=>'user_id',
    		'value' => $model->getUsername(),
    				'label' => 'Author',
    		//'value' => Html::a($model->wi_filename, 'http://pe12/workflow/' . $model->wi_file, ['style' => in_array($model->wi_status, ['OPEN', 'CLOSE']) ? '' : 'display: none;']),
    		],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'history_id',
		'label' => 'Document No.',
    'value' => ($model->getHistory()->one() ? Html::a($model->getHistory()->one()->getWi()->one()->wi_docno, ['wi/view', 'id' => $model->getHistory()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
    		[
    		'attribute'=>'status',
    		'value' => $model->status == 0 ? 'OPEN' : 'CLOSE',
    		//'value' => Html::a($model->wi_filename, 'http://pe12/workflow/' . $model->wi_file, ['style' => in_array($model->wi_status, ['OPEN', 'CLOSE']) ? '' : 'display: none;']),
    		],
    		'remark_date',
    		'feedback_date',
        'remark:ntext',
        //'status',
    		
    		
    		'feedback:ntext',
        //'flag',
    ],
    ]); ?>

    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># Detail</b>',
    'content' => $this->blocks['app\models\WiRemark'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
