<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use kartik\widgets\DatePicker;
use yii\helpers\Url;

/**
* @var yii\web\View $this
* @var app\models\WiRequest $model
* @var yii\widgets\ActiveForm $form
*/
$isClosing = false;
if(Yii::$app->controller->action->id == 'closing')
{
	$isClosing = true;
}

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>
                <?= ''; //$model->id ?>        </h2>
    </div>

    <div class="panel-body">

        <div class="wi-request-form">

            <?php $form = ActiveForm::begin([
            'id' => 'WiRequest',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error',
            		'options' => ['enctype' => 'multipart/form-data'],
            ]
            );
            ?>

            <div class="">
                <?php $this->beginBlock('main'); ?>

                <p>
                    
			<?= '';//$form->field($model, 'id')->textInput() ?>
			<?= $form->field($model, 'wi_id')->hiddenInput(['value' => $model->wi_id])->label(false);// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
/* $form->field($model, 'wi_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Wi::find()->all(), 'wi_id', 'wi_id'),
    ['prompt' => 'Select']
); */ 		?>
			<?= $form->field($model, 'wi_docno', ['horizontalCssClasses' => [
        		'wrapper' => 'col-sm-3',
    		]])->textInput(['maxlength' => true, 'readonly' => true]) ?>
    		
    		<?= $form->field($model, 'wi_model')->textarea(['rows' => 2, 'readonly' => true, 'style' => 'resize: none;']) ?>
    		
    		<?= $form->field($model, 'wi_title', ['horizontalCssClasses' => [
        		'wrapper' => 'col-sm-4',
    		]])->textInput(['maxlength' => true, 'readonly' => true]) ?>
    		
			<?= $form->field($model, 'request_type', ['horizontalCssClasses' => [
        		'wrapper' => 'col-sm-3',
    		]])->dropDownList([1 => 'CHANGE REQUEST', 2 => 'CONTROLLED COPY']) ?>
    		
    		<?= $form->field($model, 'requestor_name', ['horizontalCssClasses' => [
        		'wrapper' => 'col-sm-2',
    		]])->textInput(['readonly' => true, 'value' => $model->isNewRecord ? Yii::$app->user->identity->name : $model->requestor->name]) ?>
    		
			<?= $form->field($model, 'request_from', ['horizontalCssClasses' => [
        		'wrapper' => 'col-sm-3',
    		]])->textInput(['maxlength' => true, 'readonly' => $isClosing ? true : false]) ?>
    		
			<div class="form-group field-wirequest-request_date">
				<label class="control-label col-sm-3" for="wirequest-request_date">Request Date</label>
				<div class="col-sm-2">
					<?= DatePicker::widget([
							'name' => 'WiRequest[request_date]',
							'type' => DatePicker::TYPE_INPUT,
							//'value' => $model->wi_issue != '' ? $model->wi_issue : date('Y-m-d'),
							'value' => $model->isNewRecord ? date('Y-m-d') : $model->request_date,
							'pluginOptions' => [
									'autoclose'=>true,
									'format' => 'yyyy-mm-dd'
							],
							'options' => ['class' => 'form-control', 'disabled' => Yii::$app->controller->action->id == 'closing' ? true : false],
					])
					?>
				</div>
			</div>
			<?= '';//$form->field($model, 'requirred_date')->textInput() ?>
			<div class="form-group field-wirequest-required_date">
				<label class="control-label col-sm-3" for="wirequest-required_date">Required Date</label>
				<div class="col-sm-2">
					<?= DatePicker::widget([
							'name' => 'WiRequest[required_date]',
							'type' => DatePicker::TYPE_INPUT,
							//'value' => $model->wi_issue != '' ? $model->wi_issue : date('Y-m-d'),
							'value' => $model->required_date,
							'pluginOptions' => [
									'autoclose'=>true,
									'format' => 'yyyy-mm-dd'
							],
							'options' => ['class' => 'form-control', 'disabled' => Yii::$app->controller->action->id == 'closing' ? true : false],
					])
					?>
				</div>
			</div>
			<?= $form->field($model, 'page_no')->textInput(['maxlength' => true, 'readonly' => Yii::$app->controller->action->id == 'closing' ? true : false]) ?>
			<?= $form->field($model, 'change_item')->textarea(['rows' => 5, 'readonly' => Yii::$app->controller->action->id == 'closing' ? true : false, 'style' => 'resize: none;', 'placeholder' => 'Add <br/> to add line break...']) ?>
			<?= $form->field($model, 'reason', ['horizontalCssClasses' => [
	        		'wrapper' => 'col-sm-2',
	    		]])->dropDownList(['HILANG' => 'HILANG', 'RUSAK' => 'RUSAK', 'CORETAN/REVISI' => 'CORETAN/REVISI'], ['disabled' => Yii::$app->controller->action->id == 'closing' ? true : false]) ?>
			<?= $model->isNewRecord ? '' : $form->field($model, 'status', ['horizontalCssClasses' => [
	        		'wrapper' => 'col-sm-2',
	    		]])->dropDownList([0 => 'OPEN', 1 => 'CLOSED'], ['disabled' => Yii::$app->controller->action->id == 'closing' ? true : false]) ?>
    		
			<?= $model->isNewRecord ? '' : $form->field($model, 'uploadFile')->fileInput() ?>
			<?= $form->field($model, 'requestor_id')->hiddenInput(['value' => $model->isNewRecord ? Yii::$app->user->identity->getId() : $model->requestor_id])->label(false); ?>
                </p>
                <?php $this->endBlock(); ?>
                
                <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'WiRequest',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
                <hr/>
                <?php 
                if($isClosing)
                {
                	$btnName = 'Closing';
                }
                else 
                {
                	if($model->isNewRecord)
                	{
                		$btnName = 'Create';
                	}
                	else 
                	{
                		$btnName = 'Save';
                	}
                }
                ?>
                <?php echo $form->errorSummary($model); ?>
                <?= Html::submitButton(
                '<span class="glyphicon glyphicon-check"></span> ' .
                $btnName,
                [
                    'id' => 'save-' . $model->formName(),
                    'class' => 'btn btn-success'
                ]
                );
                ?>&nbsp;&nbsp;&nbsp;
                
                <?php echo Html::a('Cancel', Url::previous(), ['class' => 'btn btn-danger']) ?>

                <?php ActiveForm::end(); ?>

            </div>

        </div>

    </div>

</div>
