<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\WiRequest $model
*/

$this->title = 'WI Request ';// . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'WI Requests', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';

$script = <<< CSS

	table.detail-view th {
    	width: 25%;
	}
	
	table.detail-view td {
	    width: 75%;
	}

CSS;
 $this->registerCss($script);

?>
<div class="giiant-crud wi-request-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= ''; //Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id],['class' => 'btn btn-info']) ?>
        <?= ''; //Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'List WiRequests', ['index'], ['class'=>'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
                <?= $model->getWi()->one()->wi_docno ?>            </h2>
        </div>

        <div class="panel-body">



    <?php $this->beginBlock('app\models\WiRequest'); ?>

    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            //'id',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'wi_id',
	'label' => 'Doc. No.',
    'value' => ($model->getWi()->one() ? Html::a($model->getWi()->one()->wi_docno, ['wi/view', 'wi_id' => $model->getWi()->one()->wi_id,]) : '<span class="label label-warning">?</span>'),
],
        //'request_type',
    	[
    		'attribute' => 'request_type',
    		'value' => $model->request_type == 1 ? 'CHANGE REQUEST' : 'CONTROLLED COPY',
    	],
    	[
    		'attribute' => 'requestor_id',
    		'label' => 'Requestor',
    		'value' => $model->getRequestor()->one()->name,
    	],
        //'request_date',
    	[
    		'attribute' => 'request_date',
    		'value' => date('d-M-Y', strtotime($model->request_date)),
    	],
    	[
    		'attribute' => 'required_date',
    		'value' => date('d-M-Y', strtotime($model->required_date)),
    	],
    	'request_from',
        'page_no',
    	[
    		'attribute' => 'change_item',
    		'format' => 'raw',
    	],
        'reason',
    	[
    		'attribute' => 'status',
    		'value' => $model->status == 0 ? 'OPEN' : 'CLOSED',
    	],
        //'flag',
    ],
    ]); ?>

    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '. 'Detail' .'</b>',
    'content' => $this->blocks['app\models\WiRequest'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
