<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\WiPart $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>
                <?= $model->wi_part_id ?>        </h2>
    </div>

    <div class="panel-body">

        <div class="wi-part-form">

            <?php $form = ActiveForm::begin([
            'id' => 'WiPart',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error'
            ]
            );
            ?>

            <div class="">
                <?php $this->beginBlock('main'); ?>

                <p>
                    
			<?= '';//$form->field($model, 'wi_part_id')->textInput() ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'masterlist_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\WiMasterlist::find()->orderBy('doc_no ASC')->all(), 'masterlist_id', 'doc_no'),
    ['prompt' => 'Select']
); ?>
           <?php echo $form->field($model, 'part_arr')->textarea(['rows' => '6', 'style' => 'resize: vertical;']); ?>

			<?= '';// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
/* $form->field($model, 'sap_item_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\SapItem::find()->all(), 'item_id', 'item_id'),
    ['prompt' => 'Select']
); */ ?>
			<?= '';//$form->field($model, 'flag')->textInput() ?>
                </p>
                <?php $this->endBlock(); ?>
                
                <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'WiPart',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
                <hr/>
                <?php echo $form->errorSummary($model); ?>
                <?= Html::submitButton(
                '<span class="glyphicon glyphicon-check"></span> ' .
                ($model->isNewRecord ? 'Create' : 'Save'),
                [
                    'id' => 'save-' . $model->formName(),
                    'class' => 'btn btn-success'
                ]
                );
                ?>

                <?php ActiveForm::end(); ?>

            </div>

        </div>

    </div>

</div>
