<?php

use yii\helpers\Html;
use yii\helpers\Url;
//use yii\grid\GridView;
use kartik\grid\GridView;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
* @var app\models\search\WiPartSearch $searchModel
*/

$this->title = 'Wi Parts';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="giiant-crud wi-part-index">

    <?php //     echo $this->render('_search', ['model' =>$searchModel]);
    ?>

    <div class="clearfix">
        <p class="pull-left">
            <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
        </p>

        <div class="pull-right">

                                                                                
            <?= 
            \yii\bootstrap\ButtonDropdown::widget(
                [
                    'id'       => 'giiant-relations',
                    'encodeLabel' => false,
                    'label'    => '<span class="glyphicon glyphicon-paperclip"></span> ' . 'Relations',
                    'dropdown' => [
                        'options'      => [
                            'class' => 'dropdown-menu-right'
                        ],
                        'encodeLabels' => false,
                        'items'        => [            [
                'url' => ['sap-item/index'],
                'label' => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Sap Item' . '</i>',
            ],            [
                'url' => ['wi-masterlist/index'],
                'label' => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Wi Masterlist' . '</i>',
            ],]
                    ],
                    'options' => [
                        'class' => 'btn-default'
                    ]
                ]
            );
            ?>        </div>
    </div>

    
        <?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>
                    <i><?= 'Wi Parts' ?></i>
                </h2>
            </div>

            <div class="panel-body">

                <div class="table-responsive">
                <?= GridView::widget([
                'layout' => '{summary}{pager}{items}{pager}',
                'dataProvider' => $dataProvider,
                'pager'        => [
                    'class'          => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => 'First',
                    'lastPageLabel'  => 'Last'                ],
                'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                'headerRowOptions' => ['class'=>'x'],
                'columns' => [

                        [
            'class' => 'kartik\grid\ActionColumn',
			'template'=>'{view} {delete}',
            'urlCreator' => function($action, $model, $key, $index) {
                // using the column name as key, not mapping to 'id' like the standard generator
                $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                $params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
                return Url::toRoute($params);
            },
            'contentOptions' => ['nowrap'=>'nowrap']
        ],
			// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => '\kartik\grid\DataColumn',
    'attribute' => 'documentNo',
    'value' => function ($model) {
        if ($rel = $model->getMasterlist()->one()) {
            return Html::a($rel->doc_no, ['wi-masterlist/view', 'masterlist_id' => $rel->masterlist_id,], ['data-pjax' => 0, 'target' => '_blank']);
        } else {
            return '';
        }
    },
    'hAlign' => 'center',
    'format' => 'raw',
],
			// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => '\kartik\grid\DataColumn',
    'attribute' => 'partNo',
    'value' => function ($model) {
        if ($rel = $model->getSapItem()->one()) {
            return Html::a($rel->sap_partno, ['sap-item/view', 'item_id' => $rel->item_id,], ['data-pjax' => 0, 'target' => '_blank']);
        } else {
            return '';
        }
    },
    'hAlign' => 'center',
    'format' => 'raw',
],
[
'class' => '\kartik\grid\DataColumn',
'attribute' => 'partName',
	'value' => function ($model){
		return is_null($model->sapItem->description) ? '-' : $model->sapItem->description;
    },
'hAlign' => 'center',
],
			//'flag',
                ],
            ]); ?>
                </div>

            </div>

        </div>

        <?php \yii\widgets\Pjax::end() ?>

    
</div>
