<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "view_part_wi_docno".
 *
 * @property integer $wi_part_id
 * @property string $sap_partno
 * @property string $sap_partname
 * @property string $wi_docno
 * @property string $wi_title
 * @property string $wi_model
 * @property string $wi_rev
 * @property string $status_name
 * @property string $wi_issue
 * @property string $update_by_id
 * @property string $update_by_name
 * @property string $update_datetime
 */
abstract class ViewPartWiDocno extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'view_part_wi_docno';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     * @throws \yii\base\InvalidConfigException
     */
    public static function getDb()
    {
        return Yii::$app->get('db2');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['sap_partno', 'sap_partname', 'wi_docno', 'wi_title', 'wi_model', 'wi_rev', 'status_name', 'wi_issue', 'update_by_id', 'update_by_name', 'update_datetime'], 'default', 'value' => null],
            [['wi_part_id'], 'default', 'value' => 0],
            [['wi_part_id'], 'integer'],
            [['wi_model'], 'string'],
            [['wi_issue', 'update_datetime'], 'safe'],
            [['sap_partno'], 'string', 'max' => 15],
            [['sap_partname'], 'string', 'max' => 255],
            [['wi_docno', 'update_by_id'], 'string', 'max' => 50],
            [['wi_title'], 'string', 'max' => 200],
            [['wi_rev'], 'string', 'max' => 5],
            [['status_name'], 'string', 'max' => 30],
            [['update_by_name'], 'string', 'max' => 150]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'wi_part_id' => 'Wi Part ID',
            'sap_partno' => 'Sap Partno',
            'sap_partname' => 'Sap Partname',
            'wi_docno' => 'Wi Docno',
            'wi_title' => 'Wi Title',
            'wi_model' => 'Wi Model',
            'wi_rev' => 'Wi Rev',
            'status_name' => 'Status Name',
            'wi_issue' => 'Wi Issue',
            'update_by_id' => 'Update By ID',
            'update_by_name' => 'Update By Name',
            'update_datetime' => 'Update Datetime',
        ]);
    }

}
