<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "wi_removal_tbl".
 *
 * @property integer $id
 * @property integer $wi_id
 * @property string $issue_date
 * @property string $doc_no
 * @property string $doc_title
 * @property string $doc_model
 * @property string $doc_section
 * @property string $doc_stage
 * @property integer $doc_rev
 * @property string $doc_rev_pageno
 * @property string $doc_maker
 * @property string $doc_copy_qty
 * @property string $remove_status
 * @property string $remove_by_id
 * @property string $remove_by_name
 * @property string $remove_datetime
 * @property string $remove_remark
 * @property string $remove_pic
 * @property string $create_datetime
 * @property string $aliasModel
 */
abstract class WiRemovalTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wi_removal_tbl';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db2');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['wi_id', 'doc_rev'], 'integer'],
            [['issue_date', 'remove_datetime', 'create_datetime'], 'safe'],
            [['doc_no', 'remove_by_name'], 'string', 'max' => 150],
            [['doc_title', 'remove_remark'], 'string', 'max' => 255],
            [['doc_model', 'doc_section', 'doc_stage', 'doc_rev_pageno', 'doc_maker', 'doc_copy_qty', 'remove_by_id', 'remove_pic'], 'string', 'max' => 50],
            [['remove_status'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'wi_id' => 'Wi ID',
            'issue_date' => 'Issue Date',
            'doc_no' => 'Doc No',
            'doc_title' => 'Doc Title',
            'doc_model' => 'Doc Model',
            'doc_section' => 'Doc Section',
            'doc_stage' => 'Doc Stage',
            'doc_rev' => 'Doc Rev',
            'doc_rev_pageno' => 'Doc Rev Pageno',
            'doc_maker' => 'Doc Maker',
            'doc_copy_qty' => 'Doc Copy Qty',
            'remove_status' => 'Remove Status',
            'remove_by_id' => 'Remove By ID',
            'remove_by_name' => 'Remove By Name',
            'remove_datetime' => 'Remove Datetime',
            'remove_remark' => 'Remove Remark',
            'remove_pic' => 'Remove Pic',
            'create_datetime' => 'Create Datetime',
        ];
    }




}
