<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\WiMasterlist $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>
                <?= $model->masterlist_id ?>        </h2>
    </div>

    <div class="panel-body">

        <div class="wi-masterlist-form">

            <?php $form = ActiveForm::begin([
            'id' => 'WiMasterlist',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error'
            ]
            );
            ?>

            <div class="">
                <?php $this->beginBlock('main'); ?>

                <p>
                    
			<?= $form->field($model, 'masterlist_id')->hiddenInput()->label(false) ?>
			<?= $form->field($model, 'doc_no')->textInput(['maxlength' => true, 'readonly' => true]) ?>
			<?= $form->field($model, 'doc_title')->textInput(['maxlength' => true]) ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'doc_class')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\DocClass::find()->orderBy('class_code')->all(), 'doc_class_id', 'dropdownLabel'),
    ['prompt' => 'Select']
); ?>
			<?= $form->field($model, 'speaker_model')->textarea(['rows' => 6]) ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'doc_section')->dropDownList(ArrayHelper::map(app\models\DocSection::find()->where(['flag' => 1])->orderBy('section_name')->all(), 'doc_section_id', 'section_name'),
['prompt' => 'Select']); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'doc_type')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\DocType::find()->orderBy('type_name')->all(), 'doc_type_id', 'type_name'),
    ['prompt' => 'Select']
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'pic_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\User::find()->where(['role_id' => 4])->orderBy('name')->all(), 'id', 'name'),
    ['prompt' => 'Select']
); ?>
			<?= $form->field($model, 'date_modified')->hiddenInput()->label(false) ?>
			<?= $form->field($model, 'user_id')->hiddenInput()->label(false) ?>
			<?= $form->field($model, 'flag')->hiddenInput(['value' => 1])->label(false) ?>
                </p>
                <?php $this->endBlock(); ?>
                
                <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'Form WI Masterlist',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
                <hr/>
                <?php echo $form->errorSummary($model); ?>
                <?= Html::submitButton(
                '<span class="glyphicon glyphicon-check"></span> ' .
                ($model->isNewRecord ? 'Create' : 'Save'),
                [
                    'id' => 'save-' . $model->formName(),
                    'class' => 'btn btn-success'
                ]
                );
                ?>

                <?php ActiveForm::end(); ?>

            </div>

        </div>

    </div>

</div>
